name: Run Gradle Build
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Java
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        name: Upload built mod JAR
        with:
          name: mod-jar
          path: build/libs/*.jar