name: Initialize Template Repo
on:
  - push

permissions:
  contents: write

jobs:
  cleanup:
    name: "Initialize Repo"
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'Forge1.8.9Template'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          owner=$(echo $GITHUB_REPOSITORY | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')
          name=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | tr '[:upper:]' '[:lower:]' | tr -d "-" | tr -d ".")
          pack_name="com.github.${owner,,}.${name,,}"
          proj_name="$(echo $GITHUB_REPOSITORY | cut -d/ -f2)"
          modid="$(echo $name | sed 's/[^a-z]//g')"
          ./make-my-own.sh "$pack_name" "$proj_name" "$modid"
          git add .
          git commit -F- <<EOF
          Initialize template repository proper
          
          Set package name to $pack_name
          Set project name to $proj_name
          Set modid to $modid
          EOF
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
